### ISSUE TITLE
提交自己的github用户名在这里

### ISSUE THREAD

**Issue by ouyangzhiping** [AIWriter/OMOOC.Writer.QA#1]
示范：

ouyangzhiping

**Comment by wwulfric** [comment]
wwulfric

**Comment by jude90** [comment]
jude90

**Comment by zxmio** [comment]
sunnydust

**Comment by lycheew** [comment]
lycheew

**Comment by zhoubaobao** [comment]
zhoubaobao

**Comment by timmy3131** [comment]
timmy3131

**Comment by asaphzhang** [comment]
asaphzhang

**Comment by ouyangzhiping** [comment]
棒！

**Comment by corwin1949** [comment]
xinghai1949

**Comment by yangyunxuan** [comment]
yangyunxuan

**Comment by JoanneYuan** [comment]
JoanneYuan

**Comment by sky-null** [comment]
Xuwudao

**Comment by qxiaoxiao** [comment]
qxiaoxiao

**Comment by VikingMew** [comment]
vikingmew

**Comment by heshuxia** [comment]
heshuxia

**Comment by DukeeLimboo** [comment]
DukeeLimboo

**Comment by xiaozhenliu** [comment]
xiaozhenliu

**Comment by caosbad** [comment]
imcaos

**Comment by XinnanNiu** [comment]
XinnanNiu

**Comment by sunnyhuang42** [comment]
ishanshan

**Comment by rampagepeter** [comment]
rampagepeter

**Comment by complexly** [comment]
complexly

**Comment by sisisimao** [comment]
sisisimao

**Comment by rui420** [comment]
rui420

**Comment by phoebeyeah** [comment]
phoebeyeah

**Comment by cici1989** [comment]
cici1989

**Comment by stonejiajia** [comment]
StoneJiaJia

**Comment by chuxiaoli** [comment]
chuxiaoli

**Comment by gaohezhe** [comment]
gaohezhe

**Comment by xuhuixian** [comment]
xuhuixian

**Comment by shuosong0532** [comment]
misstianna

**Comment by yeyangruofeng** [comment]
yeyangruofeng

**Comment by xyviva** [comment]
xyviva

**Comment by StellaShi** [comment]
StellaShi

**Comment by zhoubaobao** [comment]
zhoubaobao

**Comment by cuihanimath** [comment]
Cuihanimath@gmail.com

**Comment by ouyangzhiping** [comment]
棒！

**Comment by ouyangzhiping** [comment]
标记为棒的，以上的学员均已手动添加。

**Comment by ZoomQuiet** [comment]
ZoomQuiet

2015-06-10 18:44 GMT+08:00 Zhiping Yang notifications@github.com:

> 标记为棒的，以上的学员均已手动添加。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenMindClub/OMOOC.Writer.QA/issues/1#issuecomment-110695776
> .

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by balsamleo** [comment]
balsamleo

**Comment by balsamleo** [comment]
balsamleo

**Comment by cnfeat** [comment]
cnfeat

**Comment by Time-lady** [comment]
Time-lady

**Comment by dadago2015** [comment]
dadago2015

**Comment by ouyangzhiping** [comment]
棒！标记为棒的，以上的学员均已手动添加。

**Comment by yzha3917** [comment]
yzha3917
刚刚似乎留错地方了...

**Comment by StellaShi** [comment]
再留一遍：stellashi

**Comment by yangshaoshun** [comment]
yangshaoshun

**Comment by gaohezhe** [comment]
gaohezhe

**Comment by libiqin** [comment]
libiqin

**Comment by Silencetodd** [comment]
silencetodd

**Comment by KellyZhangQY** [comment]
KellyZhangQY

**Comment by ouyangzhiping** [comment]
棒！标记为棒的，以上的学员均已手动添加。

**Comment by yangyunxuan** [comment]
没有收到通知，再留一遍：yangyunxuan

**Comment by xiaofeiyu** [comment]
xiaofeiyu

**Comment by belenshi** [comment]
belenshi

**Comment by zshaolin** [comment]
zshaolin

**Comment by badboy315** [comment]
badboy315

**Comment by xyviva** [comment]
未收到邀请，再留一次：xyviva

**Comment by dadago2015** [comment]
dadago2015  未收到邀请，再留一次

**Comment by Jessiehao** [comment]
Jessiehao

**Comment by jianjiao2021** [comment]
jianjiao2021

**Comment by kidult00** [comment]
kidult00

**Comment by 0zonebilly** [comment]
0zonebilly

**Comment by shuosong0532** [comment]
未收到+1，再留一次~ misstianna

**Comment by picklecai** [comment]
picklecai

**Comment by betterweishu** [comment]
betterweishu

**Comment by YixuanFranco** [comment]
YixuanBurnett

**Comment by Rainvoo** [comment]
Rainvoo

**Comment by csufuyi** [comment]
csufuyi

**Comment by ouyangzhiping** [comment]
棒！标记为棒的，以上的学员均已手动添加。

**Comment by susansecret** [comment]
susansecret

**Comment by weizhh** [comment]
weizhh

**Comment by dadago2015** [comment]
dadago2015

**Comment by xiaofeiyu** [comment]
没有收到，再次添加xiaofeiyu

**Comment by sundevilyang** [comment]
sundevilyang

**Comment by Danyang25Zhao** [comment]
danyang25zhao

**Comment by toytao** [comment]
toytao

**Comment by weizhh** [comment]
weizhh

again

**Comment by shuosong0532** [comment]
终于解决了注册邮箱的bug,求阳老辛苦再添加一遍~  
misstianna

**Comment by zhuzuojun** [comment]
zhuzuojun

**Comment by scottming** [comment]
scottming

**Comment by xiexingzhi** [comment]
xiexingzhi

**Comment by xiexingzhi** [comment]
xiexingzhi

**Comment by liusansan** [comment]
liusansan

**Comment by ouyangzhiping** [comment]
棒！标记为棒的，以上的学员均已手动添加。

**Comment by gaohezhe** [comment]
Helen-gao

**Comment by gaohezhe** [comment]
gao-hezhe

**Comment by yuyandong** [comment]
ARVN

PS:原来要重新加啊

**Comment by picklecai** [comment]
gmail变成primary后，要重新邀请的吗？picklecai

**Comment by richardbeijing** [comment]
richardbeijing

**Comment by gao-hezhe** [comment]
gao-hezhe

**Comment by MythJune** [comment]
MythJune

**Comment by gaohezhe** [comment]
gao-hezhe

**Comment by weizhh** [comment]
weizhh
没收到，再来一遍

**Comment by wwulfric** [comment]
没收到再来 wwulfric

**Comment by liyaokaka** [comment]
liyaokaka   谢谢阳老

**Comment by JC-Yuen** [comment]
JC-Yuen

**Comment by yangyunxuan** [comment]
yangyunxuan ，谢谢阳老

**Comment by VeronicaHsu** [comment]
VeronicaHsu

**Comment by liucx1031** [comment]
liucx1031

**Comment by xyviva** [comment]
xyviva, 换成gmail邮箱

**Comment by bugeb** [comment]
lttowq

**Comment by yangtzehina** [comment]
yangtzehina

**Comment by xyviva** [comment]
xyviva

**Comment by kelinda** [comment]
kelinda

**Comment by demo-pan** [comment]
demo-pan

**Comment by kelinda** [comment]
Kelinda再一次，还是没有收到邀请呢，麻烦老师了

**Comment by ouyangzhiping** [comment]
棒！标记为棒的，以上的学员均已手动添加。

**Comment by yangtzehina** [comment]
Github:    yangtzehina

 

发件人: Zhiping Yang [mailto:notifications@github.com] 
发送时间: 2015年6月11日 0:19
收件人: OpenMindClub/OMOOC.Writer.QA
抄送: yangtzehina
主题: Re: [OMOOC.Writer.QA] 提交自己的github用户名在这里 (#1)

 

棒！标记为棒的，以上的学员均已手动添加。

**Comment by zsisi** [comment]
zsisi

**Comment by MythJune** [comment]
MythJune ，麻烦阳老再邀请一遍。谢谢！

**Comment by picklecai** [comment]
是不是昨天下午fork的不删掉邮箱就收不到啊？刚刚才删掉那个，麻烦阳老再邀请一下：picklecai。O(∩_∩)O谢谢

**Comment by caicono** [comment]
caicono

**Comment by wdcheng1** [comment]
wdcheng1

**Comment by mammoth2008** [comment]
mammoth2008

**Comment by xiaokechenchen** [comment]
xiaokechenchen

**Comment by 4plus-ma** [comment]
4plus-ma

**Comment by xyviva** [comment]
xyviva

**Comment by ouyangzhiping** [comment]
棒！标记为棒的，以上的学员均已手动添加。

**Comment by yangyunxuan01** [comment]
yangyunxuan01

**Comment by pezy** [comment]
pezy

**Comment by dadago2015** [comment]
dadago2015  麻烦阳老再邀请一遍。谢谢！

**Comment by foxsshome** [comment]
foxsshome

**Comment by fengguang22** [comment]
fengguang22

**Comment by shuosong0532** [comment]
misstianna
我换成了gmail邮箱，麻烦阳老再试一遍~

**Comment by zheyiyi** [comment]
zheyiyi

**Comment by picklecai** [comment]
picklecai

**Comment by zheyiyi** [comment]
lisheng

**Comment by picklecai** [comment]
换qq邮箱了，麻烦阳老再试一遍：picklecai

**Comment by FionaQu** [comment]
FionaQu

**Comment by zxcbbn** [comment]
zxcbbn

**Comment by yangtzehina** [comment]
yangtzehina   没有收到邀请

 

发件人: Zhiping Yang [mailto:notifications@github.com] 
发送时间: 2015年6月11日 8:51
收件人: OpenMindClub/OMOOC.Writer.QA
抄送: yangtzehina
主题: Re: [OMOOC.Writer.QA] 提交自己的github用户名在这里 (#1)

 

棒！标记为棒的，以上的学员均已手动添加。

**Comment by yangtzehina** [comment]
yangtzehina 没有收到邀请，在发一次

**Comment by yangtzehina** [comment]
yangtzehina   没有收到邀请，在发一次

 

发件人: Zhiping Yang [mailto:notifications@github.com] 
发送时间: 2015年6月11日 8:51
收件人: OpenMindClub/OMOOC.Writer.QA
抄送: yangtzehina
主题: Re: [OMOOC.Writer.QA] 提交自己的github用户名在这里 (#1)

 

棒！标记为棒的，以上的学员均已手动添加。

**Comment by chaonet** [comment]
chaonet

**Comment by xyviva** [comment]
再试一次，主力邮箱换成qq邮箱，xyviva

**Comment by Wangqiaoyang** [comment]
wangqiaoyang

**Comment by Wangqiaoyang** [comment]
Wangqiaoyang

**Comment by chenyan555** [comment]
chenyan555

**Comment by ouyangzhiping** [comment]
棒！标记为棒的，以上的学员均已手动添加。

**Comment by zhlide** [comment]
zhlide

**Comment by ouyangzhiping** [comment]
棒！标记为棒的，以上的学员均已手动添加。

**Comment by liryyy** [comment]
wangyujie123

**Comment by TaoPeng9** [comment]
taopeng

**Comment by TaoPeng9** [comment]
taopeng9

**Comment by zhlide** [comment]
zhlide

**Comment by picklecai** [comment]
阳老，反复换了邮箱收不到邀请邮件。
是不是之前的邀请邮件丢了，要取消之前的邀请，再重新发一下邀请？麻烦阳老再操作一下，O(∩_∩)O谢谢
picklecai

**Comment by EddyZX** [comment]
EddyZX

**Comment by Marxxy** [comment]
Marxxy,重新注册了一个github账号，麻烦阳老再邀请一下。

**Comment by megancai** [comment]
麻烦阳老再邀请一下，重新注册的号：megancai

**Comment by dadago2015** [comment]
dadago2015 换邮箱

**Comment by hades-hy** [comment]
这个号收不到验证邮件，已经换成hazel-hy，邮箱:hazel19940806@gmail.com

**Comment by helenysli** [comment]
helenysli

**Comment by hazel-hy** [comment]
更换用户名和邮箱，hazel-hy，邀请邮件请发hazel19940806@gmail.com

**Comment by chenziheng** [comment]
chenziheng

**Comment by tonyyet** [comment]
tonyyet

**Comment by chaonet** [comment]
chaonet，重发一次

**Comment by garyhong15** [comment]
garyhong15

**Comment by chenziheng** [comment]
chenziheng 重发

**Comment by tornoteli** [comment]
tornoteli

**Comment by zsisi** [comment]
zsisi

2015-06-11 21:58 GMT+08:00 chenziheng notifications@github.com:

**Comment by sunnyhuang42** [comment]
棒！标记为"棒"以上的学员均已手动添加。

**Comment by zxcbbn** [comment]
zxcbbn

**Comment by Hanmeimei920308** [comment]
Hanmeimei920308

**Comment by ipauloc** [comment]
ipauloc

**Comment by sunnyhuang42** [comment]
棒！标记为"棒"以上的学员均已手动添加

**Comment by MythJune** [comment]
报告，依然没有收到 邀请。请求再发一次邮件到 xujz2009@gmail.com，谢谢！

**Comment by biduanyun** [comment]
biduanyun

**Comment by sunmmy** [comment]
sunmmy

**Comment by Xinita9202** [comment]
Xinita9202

**Comment by runbigcat** [comment]
runbigcat

**Comment by Psychongchong531** [comment]
Psychongchong531

**Comment by sunnyhuang42** [comment]
棒！标记为"棒"以上的学员均已手动添加

**Comment by xiaomai2015** [comment]
xiaomai2015

**Comment by medsuppit** [comment]
medsuppit

**Comment by sunnyhuang42** [comment]
棒！标记为"棒"以上的学员均已手动添加

**Comment by haruhi99** [comment]
haruhi99

**Comment by ipauloc** [comment]
ipauloc

**Comment by zhengshun2016** [comment]
zhengshun002

**Comment by sunnyhuang42** [comment]
过期关闭
